### ISSUE TITLE
tip: margin shorthand syntax

### ISSUE THREAD

**Issue by 0xZakk** [jtfragale/jtfragale.github.io#3]
https://github.com/jtfragale/jtfragale.github.io/blob/0c8aadf28544c1a1c2da3a0f04d238cbf278499a/style.css#L12-L19

Instead of having both `margin-left: auto` and `margin-right: auto`, you can use the shorthand syntax, which is:

```css
img {
    margin: 0 auto;
}
```
